### PR TITLE
modulesync 2.9.0 and drop puppet 4

### PR DESCRIPTION
**Pull request by bastelfreak**
modulesync 2.7.0

### CODE REVIEW

**Comment by dhoppe** [comment]
These tests must be converted from mocha to rspec-mocks.

**Comment by alexjfisher** [comment]
@dhoppe IIRC correctly, this wasn't going to be hard to do, just quite boring for this module (loads of instances to change).

Since we're all short on time, I'm fine with using mocha for now (update `.sync.yaml` and `spec_helper.rb`)

**Comment by bastelfreak** [comment]
@alexjfisher are you able to fix the failing spec tests?

**Comment by alexjfisher** [comment]
I'll open a fresh PR.

**Comment by alexjfisher** [comment]
I have a backup of the modulesync branch I've just deleted.

**Pull request closed without merging**
