### PR TITLE
Fix merge conflicts for PR #404

### PR DESCRIPTION
**Pull request by dallinb**
@bastelfreak this should hopefully sort the problems with #404 when merging onto master.  One thing is that is happening is that the update to the gems means that the tests are now failing.  I will start working on during the week.  Would you prefer that these are fixed on this branch before you approve this merge?  Also do we want to change the default branch from 'develop' to 'master'?

### CODE REVIEW

**Comment by bastelfreak** [comment]
@dallinb yep default branch should be switched to master, which I just did. Is this PR supposed to go into develop?

**Comment by dallinb** [comment]
I've corrected the base branch.

**Comment by bastelfreak** [comment]
mhm, I don't get why travis doesn't want to start.

**Comment by dallinb** [comment]
Indeed, looks like Travis and GitHub have stopped talking to each other since the GitHub project was migrated:

```shell
08:29 $ travis requests --limit 5
push to develop rejected (Build type disabled via repository settings (push).)
  0729e03 - Release 2.6.0 (#403)
  received at: 2017-09-12 08:26:59

PR #403 approved (HEAD commit not updated)
  025856c - Merge branch 'master' into release-2.6.0
  received at: 2017-09-11 22:21:24

push to release-2.6.0 rejected (Build type disabled via repository settings (push).)
  d8b5d67 - Merge branch 'master' into release-2.6.0
  received at: 2017-09-11 22:20:37

push to gh-pages rejected (Build type disabled via repository settings (push).)
  098e105 - [strings] Generated Documentation Update at Revision 2.5.0-1-g40f8045
  received at: 2017-09-11 22:11:57

push to 2.6.0 rejected (Build type disabled via repository settings (push).)
  40f8045 - Release 2.6.0 (#402)
  received at: 2017-09-11 22:10:04
```

That date ties in with when I was preparing the 2.6.0 release to Puppet Forge.  Travis is only enabled for push requests and not pull requests.

```shell
08:29 $ travis settings
Settings for voxpupuli/puppet-cassandra:
[+] builds_only_with_travis_yml    Only run builds with a .travis.yml
[-] build_pushes                   Build pushes
[+] build_pull_requests            Build pull requests
  0 maximum_number_of_builds       Maximum number of concurrent builds
```

Short of disabling the project and re-enabling it (a sort of Travis "have you tried switching it off and on again?") I'm not sure what we can do.

**Comment by dallinb** [comment]
I've ensured that the settings for voxpupuli/puppet-cassandra are the same as those for voxpupuli/puppet-nginx. I then setup dallinb/puppet-cassandra to run against TravisCI as well (also with the same settings).  It seems branches with the new .travis.yml are not running.  I created a branch (why_no_travis) from the original master and this does attempt to build (see below):

```shell
20:41 $ travis requests
Detected repository as dallinb/puppet-cassandra, is this correct? |yes| 
push to issue-404 rejected (Branch "issue-404" not included per configuration.)
  af2e051 - Fixed issues identified by a later version of Puppet lint (#394).
  received at: 2017-09-25 20:36:16

push to why_no_travis approved (validation pending)
  40f8045 - Release 2.6.0 (#402)
  received at: 2017-09-25 20:30:07

push to issue-394_Puppet_Lint rejected (Branch "issue-394_Puppet_Lint" not included per configuration.)
  af2e051 - Fixed issues identified by a later version of Puppet lint (#394).
  received at: 2017-09-25 20:23:10
```

**Comment by bastelfreak** [comment]
so what seems to work:
* disable the required status check for travis
* disable travis as hook in github
readd travis

**Comment by bastelfreak** [comment]
You can probably fix a bunch of rubocop issues by running:

```
 bundle exec rubocop -c .rubocop.yml -D -S -a
```

**Comment by dallinb** [comment]
@bastelfreak Thank you very much for your assistance so far.  I'll work my way through the failing tests.

**Comment by dallinb** [comment]
Fixed RuboCop complaints.  Now moving onto spec tests.

**Comment by wyardley** [comment]
@dallinb bump

**Comment by dallinb** [comment]
@wyardley apologies for the long absence.  The day job is getting in the way.  I have time off next week so will continue with working on this then.

**Comment by wyardley** [comment]
@dallinb no worries, of course! Sorry to bug you about it 😉

**Pull request merged**
